### PR TITLE
Some modifications to enable toggling log output 

### PR DESCRIPTION
**Pull request by noseglasses**
To be able to wrap Kaleidoscope-Hardware-Virtual to use it as a core part of other projects, it is desirable to enable toggling any log output. 

A macro `KALEIDOSCOPE_HARDWARE_VIRTUAL_NO_LOGGING` was introduced that enables switching off any log output. Thus, the original behavior is conserved. Instead of writing to std::cout in newly written code, log output shall be performed using the two macros `KHV_LOG(...)` and `KHV_ERROR(...)`.

If `KALEIDOSCOPE_HARDWARE_VIRTUAL_NO_LOGGING` is not set, the two functions `toggleVerboseOutput(...)` and `verboseOutputEnabled()` enable to change and query the enable/disable state of logging.

### CODE REVIEW

**Comment by cdisselkoen** [comment]
I like the idea of this PR.  Some specific details:

- As in #2, we shouldn't include the deprecation message commit in this repo.
- It's unclear to me that `KHV_ERR()` messages should be guarded by `verboseOutputEnabled`.  Do we really want the ability to turn off error messages?
- I also think we should always print the prompt message and help message _when in interactive mode_, even if verbose output is disabled.
- The changes to `ConsumerControl`'s `sendReport()` and `Mouse`'s `move()` seem to be unrelated, and don't belong in a commit called "Some modifications to enable toggling log output".  Sorry to be pedantic about Git history, but clean Git history is important to me.

**Comment by obra** [comment]
"It's unclear to me that KHV_ERR() messages should be guarded by verboseOutputEnabled. Do we really want the ability to turn off error messages?"

I also wonder if it would make more sense to define kaleidoscope-wide macros for debugging output. On the device firmware side, they might get defined as Serial.prints when debugging is enabled.

(Also, I'm not personally a fan of terse names like "KHV_ERR", because they're hard to read and understand.)

**Comment by cdisselkoen** [comment]
Actually, does this have to be a macro? Could we have a log() function in Kaleidoscope-Hardware, which is implemented with stdout in Hardware-Virtual and maybe with serial in "real" hardware?

**Comment by obra** [comment]
I'd probably lift it all the way up to the kaleidoscope core, maybe modeled on a cut down set of levels modeled on syslog's levels:

log_debug('')
log_info('')
log_error('')
log_critical('')

**Comment by noseglasses** [comment]
I had good experience with log messages being wrapped in macros. To wrap KHV log messages (excluding error messages) are undesired. Macros enable switching it off. I would strongly recommend the same for Kaleidoscope as a whole. 

The deprecation message was oncluded accidentally. I still was using the old remote.

You being pedantic is absolutely ok. Sorry, I am still a github newbie. There are things I obviously have to learn the hard way ;-)

**Comment by cdisselkoen** [comment]
BTW, re: `ConsumerControl` and `Mouse` changes that ended up in this PR, I just pushed a [much-more-extensive set of changes](https://github.com/keyboardio/Kaleidoscope-Hardware-Virtual/commit/20d3ad8ba1d3e2a0fca70d72a1415ace90e9be1a) to align our `VirtualHID` with the `KeyboardioHID` versions of those classes, which have seen several API-breaking changes recently.  Hopefully this resolves build issues related to `ConsumerControl` and `Mouse`.

**Pull request closed without merging**
